### ISSUE TITLE
Pi Zero doesn't see latest voco addon

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/addon-list#1214]
Oddly, when I install Voco on a Pi Zero, it only sees version 2.2.6 instead of the latest 2.3.1. 

This is on Gateway 1.0.0.

**Comment by mrstegeman** [comment]
Any errors in the log when you're trying to install? You should be able to see the package it's pulling down.

**Comment by flatsiedatsie** [comment]
![webthings_voco_older_version](https://user-images.githubusercontent.com/805405/102389440-6d570180-3fd3-11eb-9165-b7bb74b19127.png)

**Comment by mrstegeman** [comment]
Are you able to access https://api.webthings.io:8443/addons

**Comment by flatsiedatsie** [comment]
In the log:
```
2020-12-16 19:16:37.376 ERROR  : Failed to renew certificate: Error: Failed to set DNS token on server: 404
    at Object.challengeCreateFn (/home/pi/mozilla-iot/gateway/build/webpack:/src/certificate-manager.js:298:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-12-16 19:19:29.712 INFO   : Fetching add-on https://www.candlesmarthome.com/assistant/voco-2.2.6.tgz as /tmp/zKL5vZ/voco.tar.gz
2020-12-16 19:20:50.407 INFO   : Expanding add-on /tmp/zKL5vZ/voco.tar.gz
```

**Comment by flatsiedatsie** [comment]
> Are you able to access https://api.webthings.io:8443/addons

Yes. Both on my laptop and using wget on the Pi Zero.

**Comment by flatsiedatsie** [comment]
I tried to open the full link from that screenshot. I can open it in the browser, but when I try wget, I see this:
```
pi@kitchen:~ $ wget https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7
[1] 1640
[2] 1641
[3] 1642
pi@kitchen:~ $ 
Redirecting output to 'wget-log.1'.
```

However, that log file seems ok.

```
--2020-12-16 19:25:14--  https://api.webthings.io:8443/addons?arch=linux-arm
Resolving api.webthings.io (api.webthings.io)... 18.193.161.207
Connecting to api.webthings.io (api.webthings.io)|18.193.161.207|:8443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11308 (11K) [application/json]
Saving to: 'addons?arch=linux-arm.1'

addons?arch=linux-arm.1                   100%[==================================================================================>]  11.04K  --.-KB/s    in 0.001s  

2020-12-16 19:25:15 (14.8 MB/s) - 'addons?arch=linux-arm.1' saved [11308/11308]

```

If I open the file that wget downloaded, I see this:

```
pi@kitchen:~ $ cat 'addons?arch=linux-arm.1'
[{"name":"Candle-manager-addon","display_name":"Candle manager","description":"Candle manager allows you to easily upload sketches to an Arduino.","author":"CreateCandle","homepage":"https:\/\/github.com\/createcandle\/Candle-manager-addon","packages":{"linux-arm":{"version":"1.1.0","url":"https:\/\/s3-us-west-2.amazonaws.com\/mozilla-gateway-addons\/Candle-manager-addon-1.1.0-linux-arm-v3.5.tgz","checksum":"25f66ffc2e701b2de174645589d118192ec30b11925947036ff28a467d7183eb"}},"api":2},{"name":"activitypub-adapter","display_name":"ActivityPub","description":"Send notice to Mastodon SocialWeb.","author":"Philippe Coval","homepage":"https:\/\/github.com\/rzr\/mastodon-lite","packages":{"any":{"version":"0.0.23","url":"https:\/\/github.com\/rzr\/mastodon-lite\/releases\/download\/v0.0.23\/activitypub-adapter-0.0.23.tgz","checksum":"0a244eb23cef42999d2824c37ce142c3260498a1c14e9a76afb7f7118c3302eb"}},"api":2},{"name":"cron-adapter","display_name":"Cron","description":"Allows you to use cron expressions as a trigger","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/cron-adapter#readme","packages":{"any":{"version":"0.2.5","url":"https:\/\/github.com\/tim-hellhake\/cron-adapter\/releases\/download\/0.2.5\/cron-adapter-0.2.5.tgz","checksum":"64665871cffa12b6f73630c2d5c9c17de8246d950160bad28f2cfe7636f74362"}},"api":2},{"name":"date-time-adapter","display_name":"DateTime Adapter","description":"A Date & Time adapter to create more advanced rules using sunrise, sunset, weekends, etc.","author":"tomasy","homepage":"https:\/\/github.com\/tomasy\/date-time-adapter","packages":{"any":{"version":"1.0.1","url":"https:\/\/github.com\/tomasy\/date-time-adapter\/releases\/download\/1.0.1\/date-time-adapter-1.0.1.tgz","checksum":"281ec4b3d43ff5c08790e453b52dc0868e9525a15d4c48cc0c0320f3dfb1225f"}},"api":2},{"name":"esphome-adapter","display_name":"ESPHome","description":"Connect your ESPHome (https:\/\/esphome.io\/) devices","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/esphome-adapter#readme","packages":{"any":{"version":"0.2.1","url":"https:\/\/github.com\/tim-hellhake\/esphome-adapter\/releases\/download\/0.2.1\/esphome-adapter-0.2.1.tgz","checksum":"298b1ff07556e26aac5ed380692a4d29c71a6087f96bb84e6eaeea9f70e014ba"}},"api":2},{"name":"foobot-adapter","display_name":"Foobot","description":"Adapter for Foobot Air Quality Sensors","author":"Bram van Mensvoort","homepage":"https:\/\/github.com\/bvmensvoort\/mozillaiot-foobot","packages":{"any":{"version":"0.0.2","url":"https:\/\/github.com\/bvmensvoort\/mozillaiot-foobot\/releases\/download\/v0.0.2\/foobot-adapter-0.0.2.tgz","checksum":"a36256981e43209ca4f8c3ed5a03d17d9a80ec699620b7415e68b433f2eb5359"}},"api":2},{"name":"frontier-silicon-adapter","display_name":"Frontier Silicon Internet Radio","description":"Frontier Silicon Internet Radio support","author":"bewee","homepage":"https:\/\/github.com\/bewee\/frontier-silicon-adapter","packages":{"any":{"version":"0.8.3","url":"https:\/\/github.com\/bewee\/frontier-silicon-adapter\/releases\/download\/v0.8.3\/frontier-silicon-adapter-0.8.3.tgz","checksum":"8dc4d98835fbfb1d05b83cacd24eb8c58e5145a6bce6b538f61018026848a10c"}},"api":2},{"name":"github-adapter","display_name":"GitHub","description":"Watch the issue count of your favourite GitHub repos","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/github-adapter#readme","packages":{"any":{"version":"0.2.0","url":"https:\/\/github.com\/tim-hellhake\/github-adapter\/releases\/download\/0.2.0\/github-adapter-0.2.0.tgz","checksum":"e538ab1857e86908a0cba7a94eb9f022db42f1aa8f1020bb1bbe65123b610547"}},"api":2},{"name":"input-event-adapter","display_name":"Input Event","description":"React to input events, e.g. from a USB keyboard or remote","author":"bewee","homepage":"https:\/\/github.com\/bewee\/input-event-adapter","packages":{"any":{"version":"0.2.4","url":"https:\/\/github.com\/bewee\/input-event-adapter\/releases\/download\/v0.2.4\/input-event-adapter-0.2.4.tgz","checksum":"3f71b87b6424517393d149fd9ed02032af64f0ef07fa37bf9f37b2456f9ed120"}},"api":2},{"name":"insteon-adapter","display_name":"INSTEON","description":"INSTEON device support","author":"James Willcox","homepage":"https:\/\/github.com\/snorp\/insteon-adapter","packages":{"linux-arm":{"version":"1.0.1","url":"https:\/\/s3-us-west-2.amazonaws.com\/mozilla-gateway-addons\/insteon-adapter-1.0.1-linux-arm-v8.tgz","checksum":"50d265670289000fab02805bed9565abaac4628bbc8d4de00c3e8e6fd1d78843"}},"api":2},{"name":"kodi-adapter","display_name":"Kodi","description":"Show notifications on your media player","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/kodi-adapter#readme","packages":{"any":{"version":"0.2.2","url":"https:\/\/github.com\/tim-hellhake\/kodi-adapter\/releases\/download\/0.2.2\/kodi-adapter-0.2.2.tgz","checksum":"e58b0441dca1a671b7baab62f8a9be569c9148c7870881825cf9bbba75bc01bf"}},"api":2},{"name":"lametric-adapter","display_name":"LaMetric","description":"Send notifications to your LaMetric","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/lametric-adapter#readme","packages":{"any":{"version":"0.2.1","url":"https:\/\/github.com\/tim-hellhake\/lametric-adapter\/releases\/download\/0.2.1\/lametric-adapter-0.2.1.tgz","checksum":"5d58a9f0532714bc787b102728557c15e7b74ec47023be4f881400ad3af96194"}},"api":2},{"name":"logitech-harmony-adapter","display_name":"Logitech Harmony","description":"Logitech Harmony Hub support","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/logitech-harmony-adapter#readme","packages":{"any":{"version":"0.2.10","url":"https:\/\/github.com\/tim-hellhake\/logitech-harmony-adapter\/releases\/download\/0.2.10\/logitech-harmony-adapter-0.2.10.tgz","checksum":"b04391189e4b0dfc4db0328e65f14a90884cfad53288097b0b01999505af1323"}},"api":2},{"name":"myq-adapter","display_name":"MyQ","description":"MyQ adapter add-on for WebThings Gateway","author":"Kenneth Lee","homepage":"https:\/\/github.com\/kennethklee\/webthings-myq-adapter#readme","packages":{"any":{"version":"0.1.2","url":"https:\/\/github.com\/kennethklee\/webthings-myq-adapter\/releases\/download\/v0.1.2\/myq-adapter-0.1.2.tgz","checksum":"50d78416f278bfc4517de14e8a8a30abd04380d7eadce901674395dcde48d8b6"}},"api":2},{"name":"mysensors-adapter","display_name":"MySensors","description":"Build your own smart home with this Arduino library","author":"CreateCandle","homepage":"https:\/\/github.com\/createcandle\/Webthings-mysensors-adapter","packages":{"linux-arm":{"version":"1.1.0","url":"https:\/\/s3-us-west-2.amazonaws.com\/mozilla-gateway-addons\/mysensors-adapter-1.1.0-linux-arm-v3.5.tgz","checksum":"337665b69b6638a811aeef5ec5a0610b7c85902bef3292217d232414e9289673"}},"api":2},{"name":"openuv-adapter","display_name":"OpenUV - Clear sky UV index","description":"Get the current uv index from www.openuv.io","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/openuv-adapter#readme","packages":{"any":{"version":"0.5.1","url":"https:\/\/github.com\/tim-hellhake\/openuv-adapter\/releases\/download\/0.5.1\/openuv-adapter-0.5.1.tgz","checksum":"0db1bbd40994876dd62d03c95c64d727ae2c574005a68f5756257b60f58c80da"}},"api":2},{"name":"rf433-adapter","display_name":"RF433","description":"Connect 433MHz devices to your Raspberry Pi using an rf433 board","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/rf433-adapter#readme","packages":{"linux-arm":{"version":"0.1.4","url":"https:\/\/github.com\/tim-hellhake\/rf433-adapter\/releases\/download\/0.1.4\/rf433-adapter-0.1.4.tgz","checksum":"bca62a7ecbed0f65d0f73292864168e534b51603addc70a68161af0bd47d5caf"}},"api":2},{"name":"ring-adapter","display_name":"Ring","description":"Ring device adapter for Ring Doorbells, Lights and Sirens.","author":"damooooooooooh","homepage":"https:\/\/github.com\/damooooooooooh\/ring-adapter","packages":{"any":{"version":"0.0.7","url":"https:\/\/github.com\/damooooooooooh\/ring-adapter\/releases\/download\/v0.0.7\/ring-adapter-0.0.7.tgz","checksum":"9864de69386c91abd8b74e6f27a4169e234c55ca2affe2acaba8ecbd3aad67c7"}},"api":2},{"name":"scheduler-adapter","display_name":"Scheduler","description":"Allows you to use a time schedule in your rules","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/scheduler-adapter#readme","packages":{"any":{"version":"0.1.1","url":"https:\/\/github.com\/tim-hellhake\/scheduler-adapter\/releases\/download\/0.1.1\/scheduler-adapter-0.1.1.tgz","checksum":"b470d30e63340fc18520b7ab476a75d005d90376014c8910450fbf99f15c0ab1"}},"api":2},{"name":"spotify-adapter","display_name":"Spotify","description":"Control your Spotify player","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/spotify-adapter#readme","packages":{"any":{"version":"0.5.0","url":"https:\/\/github.com\/tim-hellhake\/spotify-adapter\/releases\/download\/0.5.0\/spotify-adapter-0.5.0.tgz","checksum":"48f77c9c595e3a2602d4319289264315517d114123fc31a31ed1bd7e91eee148"}},"api":2},{"name":"tankerkoenig-adapter","display_name":"Tankerk\u00f6nig","description":"Shows you the gas prices near you (Germany only)","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/tankerkoenig-adapter#readme","packages":{"any":{"version":"0.2.4","url":"https:\/\/github.com\/tim-hellhake\/tankerkoenig-adapter\/releases\/download\/0.2.4\/tankerkoenig-adapter-0.2.4.tgz","checksum":"cc087f7973d1a578d220a37a0a4dd59b211634e44a116f84c2f0596bf308643b"}},"api":2},{"name":"tellstick-adapter","display_name":"Tellstick","description":"Telldus Tellstick adapter for WebThings Gateway. Requires telldus-core service for older generation Tellsticks.","author":"Antti Kivim\u00e4ki","homepage":"https:\/\/github.com\/majori\/tellstick-adapter","packages":{"any":{"version":"0.2.0","url":"https:\/\/github.com\/majori\/tellstick-adapter\/releases\/download\/v0.2.0\/tellstick-adapter-0.2.0.tgz","checksum":"953861609ab4e901335093b5fc27bd6f77796f23e5f5704ba89c95087ea8815f"}},"api":2},{"name":"tts-adapter","display_name":"Text-to-Speech","description":"Reads texts for you","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/tts-adapter#readme","packages":{"any":{"version":"0.1.4","url":"https:\/\/github.com\/tim-hellhake\/tts-adapter\/releases\/download\/0.1.4\/tts-adapter-0.1.4.tgz","checksum":"1a9ab5794826c6ed42c83af4e3bd8086e1f9fc6d4a5b33e7b261b85981b93011"}},"api":2},{"name":"tuya-adapter","display_name":"Tuya Smart Life","description":"Tuya Smart Life IoT devices support","author":"bewee","homepage":"https:\/\/github.com\/bewee\/tuya-adapter","packages":{"any":{"version":"0.2.4","url":"https:\/\/github.com\/bewee\/tuya-adapter\/releases\/download\/v0.2.4\/tuya-adapter-0.2.4.tgz","checksum":"2905594a1893443385c4f1cd5ed254bbdd4022b5e87520212e5a7cd8c9d0ab25"}},"api":2},{"name":"yamaha-adapter","display_name":"Yamaha","description":"Connect your yamaha audio devices","author":"Tim Hellhake","homepage":"https:\/\/github.com\/tim-hellhake\/yamaha-adapter#readme","packages":{"any":{"version":"0.2.0","url":"https:\/\/github.com\/tim-hellhake\/yamaha-adapter\/releases\/download\/0.2.0\/yamaha-adapter-0.2.0.tgz","checksum":"6bf7adc14cfa1bda1a1f6625f2ea23e1ee7c376a127fbcba94391390f828f6d2"}},"api":2}]
```

Oddly, that doesn't mention voco.

**Comment by mrstegeman** [comment]
Wrap the URL in quotes when you’re using wget.

**Comment by flatsiedatsie** [comment]
However, if I open the link, I do see the voco  addon:

https://api.webthings.io:8443/addons?arch=linux-arm&version=1.0.0&node=64&python=2.7%2C3.7

**Comment by flatsiedatsie** [comment]
It actually seems like none of the latest addon versions are showing up at that URL. For example, `airport` is still at version 0.1.1.

**Comment by mrstegeman** [comment]
Should be fixed now.

**Comment by flatsiedatsie** [comment]
It is. Thanks!
